name: MacOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:      
  MacOS:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler:
          - Xcode_10.3
          - Xcode_11.7
          - Xcode_12.4

    env:
      CXXFLAGS: -std=c++11

    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/${{ matrix.compiler }}.app/Contents/Developer
      - run: cmake -DTERMCOLOR_TESTS=ON .
      - run: cmake --build .
      - run: ./test_termcolor
      
