name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:  
  Ubuntu-Clang:
    strategy:
      matrix:
        include:
          - clang-compiler: "6.0"
            ubuntu-release: ubuntu-20.04
          - clang-compiler: "7"
            ubuntu-release: ubuntu-20.04
          - clang-compiler: "8"
            ubuntu-release: ubuntu-20.04
          - clang-compiler: "9"
            ubuntu-release: ubuntu-20.04
          - clang-compiler: "10"
            ubuntu-release: ubuntu-20.04
          - clang-compiler: "11"
            ubuntu-release: ubuntu-22.04
          - clang-compiler: "12"
            ubuntu-release: ubuntu-22.04
          - clang-compiler: "13"
            ubuntu-release: ubuntu-22.04
          - clang-compiler: "14"
            ubuntu-release: ubuntu-22.04
          - clang-compiler: "15"
            ubuntu-release: ubuntu-22.04
          - clang-compiler: "16"
            ubuntu-release: ubuntu-24.04
          - clang-compiler: "17"
            ubuntu-release: ubuntu-24.04
          - clang-compiler: "18"
            ubuntu-release: ubuntu-24.04

    env:
      CXX: clang++-${{ matrix.clang-compiler }}
      CXXFLAGS: -std=c++11

    runs-on: ${{ matrix.ubuntu-release }}

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt -y install clang-${{ matrix.clang-compiler }}
      - run: cmake -DTERMCOLOR_TESTS=ON .
      - run: cmake --build .
      - run: ./test_termcolor

  Ubuntu-GCC:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc-compiler:
          - "10"
          - "11"
          - "12"

    env:
      CXX: g++-${{ matrix.gcc-compiler }}
      CXXFLAGS: -std=c++11

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt -y install g++-${{ matrix.gcc-compiler }}
      - run: cmake -DTERMCOLOR_TESTS=ON .
      - run: cmake --build .
      - run: ./test_termcolor
